version: '3.3'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: movies
    volumes:
      - sock:/sock
      - data:/data
    networks:
      - app

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
    networks:
      - app

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - sock:/sock
      - ./backend:/var/www
    ports:
      - 3000:3000
    networks:
      - app
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 80:8080
    volumes:
      - sock:/sock
    restart: always
    networks:
      - app
    depends_on:
      - backend

volumes:
  sock:
  data:

networks:
  app:
