version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - data:/data/postgres
    env_file:
      - docker.env
    networks:
      - app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - http.port=9200
      - http.cors.allow-origin=*
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - app

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - sock:/sock
      - ./backend:/var/www
    ports:
      - 3000:3000
    networks:
      - app
    depends_on:
      - postgres
      - elasticsearch

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 80:8080
    volumes:
      - sock:/sock
    restart: always
    networks:
      - app
    depends_on:
      - backend

volumes:
  sock:
  data:
  esdata:

networks:
  app:
